#!/bin/sh
wal -i  $HOME/pix/wall/wall.png

sed -i 'N;$!P;D' $HOME/.cache/wal/colors-wal-dwm.h
(cd $HOME/.config/src/dwm && sudo cp config.def.h config.h && sudo make install)
(cd $HOME/.config/src/st && sudo cp config.def.h config.h && sudo make install)
(cd $HOME/.config/src/dmenu && sudo cp config.def.h config.h && sudo make install)
